# Site
repository: sproogen/resume-theme
favicon: images/faviconn.ico

# Content configuration version
version: 2

# Personal info
name: Ashraful Islam Rafi
title: MSCS'24 @ UAB | Actively Seeking Full-Time Software Engineering Roles
email: ashrafulrafi@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: ashraful-islam-rafi
linkedin_username: ashraful-islam-rafi
# twitter_username: rafithe47
# instagram_username: rafithe47
# facebook_username: rafithe47
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# flickr_username: jekyll
# instagram_username: rafithe47
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: GitLab Link
#   icon: fab fa-gitlab
#   url: https://gitlab.com/rafithe47

- title: Resume 
  icon: far fa-file-pdf
  url: https://ashraful-islam-rafi.github.io/Ashraful_Islam_resume.pdf

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
# Starts from here
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs  
  Software engineer with 7+ years of experience in system design, full-stack development, and DevOps. Proven expertise in building scalable, user-friendly applications and delivering impactful solutions across diverse domains.

  Currently seeking <mark>Software Engineering</mark>, <mark>Full Stack Developer</mark>, or <mark>Internship</mark> opportunities to apply my skills, embrace new challenges, and continue growing professionally.

  Graduated in <mark>December 2024</mark> and available for full-time employment starting <mark>January 13, 2025</mark>. 

# <br/>
# # I am most skilled in: <mark>Research, Developing Software</mark> and <mark>Eating Pizza</mark> ðŸ•

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Alabama at Birmingham
        link: www.uab.edu
        sub_title: Teaching Assistant
        caption: August 26 - Present
        
        description: | # this will include new lines to allow paragraphs
           - Assisting [Dr. Li](https://lixi1994.github.io){:target="_blank" rel="noopener"} with course materials, grading, and holding office hours for the **Foundation of Data Science** course.

        # - Assisting Professor [Xi Li](https://lixi1994.github.io){:target="_blank" rel="noopener"} in preparing course materials, grading, and conducting office hours for **CS685/785 Foundation of Data Science**, supporting and guiding over 290 students on key concepts.

        # - Holding weekly office hours, offering one-on-one and group assistance to students, ensuring comprehension of complex topics.

        # - Collaborating with the professor to enhance teaching methods and improve student engagement.

        # - Assisting students with programming tasks using Python and libraries like Pandas, NumPy, and scikit-learn.


      - layout: left
        title: University of Alabama at Birmingham
        link: www.uab.edu
        # link_text: Search Engine Pipilika 
        sub_title: Graduate Research Assistant
        caption: January 2022 - August 25
        # caption: August 2017 - March 2021
        
        description: | # this will include new lines to allow paragraphs
          - **Brouhaha:** Led a team of three to develop Brouhaha, a Racket-to-C++ compiler, optimizing compilation speed with advanced inlining techniques and control-flow-driven performance improvements. [Github Link](https://github.com/harp-lab/brouhaha){:target="_blank" rel="noopener"}

          - **DevOps and Build Optimization:** Used Git, Docker, and CMake to build and deploy Brouhaha, ensuring compatibility across Linux, Windows, and macOS.

          - **Test Automation and Validation:** Wrote Python scripts to automate testing for Brouhaha, improving validation accuracy and debugging efficiency.  
             
          - **Survey on Functional Compilation and Functional Program Analysis:** Reviewed over 120 research papers to extract insights on software optimization techniques and applied findings to improve compiler performance. [Survey Link](https://ashraful-islam-rafi.github.io/Survey.pdf){:target="_blank" rel="noopener"}


        # - **Teaching Experience:** Conducted 5 lab classes for the Programming Languages (CS401) course during Spring 2023.
        # - **Compiler:** Developed a functional compiler translating a minimal Racket-like language to C++, ensuring identical outputs. [Github Link](https://github.com/ashraful-islam-rafi/compiler){:target="_blank" rel="noopener"}

      - layout: left
        title: Bangla Search Engine (Pipilika)
        link: https://en.wikipedia.org/wiki/Pipilika
        # link_text: Search Engine Pipilika 
        sub_title: Software Engineer
        # caption: August 2017 - Present
        caption: August 2017 - March 2021
        
        # quote: >
        #   Pipilika is a search engine operated from Sylhet, Bangladesh. It is the country's first Bangla search engine developed by the Computer Science and Engineering students of Shahjalal University of Science and Technology, Sylhet

        description: | # this will include new lines to allow paragraphs
          - **Search Relevancy Improvement:** Enhanced keyword-based search relevancy by 35% through redesigning the Apache Solr schema and implementing query-boosting techniques.
 
          - **Large-Scale Data Search Portal:** Built scalable crawlers and parsers with Python and Java to extract data from over 40,000 websites, increasing indexed data by 18% and improving search functionality.
 
          - **RESTful APIs:** Developed multiple RESTful APIs with Spring Boot for data processing, reporting, and integration, enhancing system performance and usability.
 
          - **Rich Document Parser:** Extracted Bangla Unicode data from files (PDF, DOC, PPT, CSV) using Jsoup, achieving a 25% improvement in relevant search query matches. 

          - **TIG Stack Deployment:** Deployed the TIG stack (Telegraf, InfluxDB, Grafana) for real-time infrastructure monitoring, cutting downtime by 15% through proactive issue detection.

        # **Spellchecker Context-Aware Library:** Reduced the Dictionary file loading time by 20 seconds, by fixing various bugs.
 


      - layout: left
        title: Southeast University
        link: https://seu.edu.bd
        # link_text: Southeast University, Bangladesh
        sub_title: Programmer
        caption: April 2015 - August 2017
        

        description: | # this will include new lines to allow paragraphs    
          - Developed an online admission system using PHP, MySQL, and Bootstrap3, increasing admissions by 25%.
          
          - Optimized the University Support System by redesigning the MySQL schema, reducing report generation time by 30%.

          - Supervised a vendor to deliver a Human Resources Management System on time, meeting university requirements.

          - Acted as Interim IT Manager for over three months, overseeing daily operations and ensuring uninterrupted services across all functions.

      # - layout: left
      #   title: DURBAR SOFTWARE
      #   link: https://durbar.co
      #   # link_text: Durbar Software, Bangladesh
      #   sub_title: Senior Software Engineer
      #   caption: Novermber 2014 - April 2015
        

      #   description: | # this will include new lines to allow paragraphs
      #     - Developed the annual **Local Health Bulletin Report (2015)** and **Photo Archiver System** for the Ministry of Health and Family Welfare, Government of Bangladesh.

      #     - Enhanced cross-platform compatibility by integrating Bootstrap3, resulting in a 40% increase in mobile user engagement.


      - layout: left
        title: IT Lab Solutions Ltd
        link: www.itlabsolutions.com
        # link_text: IT Lab Solutions Ltd.
        sub_title: Software Developer
        caption: September 2013 - December 2014
        

        description: | # this will include new lines to allow paragraphs
          - Developed web-based shop management software for over 5 businesses using CodeIgniter, MySQL, and Bootstrap3, providing solutions for inventory, sales, and reporting.
          

  - title: Skills # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      - **Programming Languages:** Python, Java, C, C++, PHP, JavaScript, Racket
      - **Databases:** MySQL (RDBMS), MongoDB (NoSQL), Apache Solr (NoSQL)
      - **Frameworks & Libraries:** Spring Boot, React, WordPress, CodeIgniter, Bootstrap3, AJAX, jQuery
      - **DS & ML Libraries:** NumPy, Pandas, Scikit-learn, SciPy, Matplotlib, Seaborn, TensorFlow, PyTorch   
      - **Web development:** RESTful APIs, Postman, HTML5, CSS3, JSON, Web Scraping (Scrapy, Jsoup)
      - **Project Management & Methodologies:** Agile, Scrum, SDLC, MVC, Unit Testing (Pytest, Junit), JIRA
      - **DevOps:** Git, Docker, AWS (S3, EC2, Lambda, SNS), Linux, CI/CD, Maven, Bash, OpenMPI, CMake, Apache, Tomcat, LAMP

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: University of Alabama at Birmingham
        sub_title: Master of Science in Computer Science
        link: www.uab.edu
        caption: January 2022 - December 2024 (GPA 3.80/4.00)

      # - layout: top-middle
      #   title: LEADING UNIVERSITY
      #   link: www.lus.ac.bd
      #   # link_text: Leading University, Sylhet
      #   # caption: CGPA - 3.30 out of 4.00 <br/>2009 - 2013 
      #   caption: August 2009 - August 2013 
      #   sub_title: BS in Computer Science and Engineering

      #   # quote: >
      #   #   Leading University or LU is a private university in Bangladesh. It was established in 2001 under the Private University Act 1992. The campus of LU is located in Ragib Nagar, Kamal Bazar, South Surma, Sylhet, Bangladesh
      #   description: | # this will include new lines to allow paragraphs
      #     During my time at Leading University, I learned most of the key skills that have I have taken through my career such as programming, teamwork, and working to tight deadlines. I was actively involved with various voluntary services as well.

    #       <br/> 
    #       **Thesis/Project Title:** System to Secure Web Authentication: using cache, cookie, and session <br/>
    

  - title: Extracurricular / Activities # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      - Served as a **Judge** for the Fall 2024 Undergraduate Research Expo at UAB, evaluating student research projects.

      - Served as a **Judge** for the Summer 2023 Undergraduate Research Expo at UAB, evaluating student research projects.
      
      - Acted as a **Treasurer** for the Bangladesh Student Association at UAB (2022-23), overseeing finances and budgeting.

  # - Conducted over 15 workshops as a **Programming Tutor** at Leading University Computer Club (2012-13), focusing on Data Structures and Algorithms.


  # - **Tutor:** Conducted over 15 programming workshops focused on Data Structures and Algorithms at Leading University, with each session attended by more than 40 students.

  # - **Contest Participation:** Competed in various national and inter-university programming contests, including IUT 4th National ICT Fest (2012), NSU ACM ICPC Dhaka Site (2011), SUST Inter-University Programming Contest (2011), and IUT Inter-University Programming Contest (2011).

  # - **Public Relations Officer:** Coordinated and managed 3 Intra-university programming contests for the Leading University Computer Club (LUCC).



  # - title: Relevant Coursework # Title for the section
  #   layout: text # Type of content section (list/text)
  #   content: |
  #     - Advanced Algorithms & Apps, Foundations of Data Science, Data Mining, Artificial Intelligence with Prolog, Data Structure and Algorithms, Computer Algorithms and Complexity, Structure Programming C, Object Oriented Programming - C++, Java Programming, Operating Systems,  Database Management System, Software Engineering, and System Analysis, Design and Development


  # - title: Research Interest # Title for the section
  #   layout: text # Type of content section (list/text)
  #   content: |
  #     - Programming Languages, Software Engineering, High-Performance Computing, Machine Learning, Information Retrieval, and Human-Computer Interaction

  # - title: Voluntary Services # Title for the section
  #   layout: text # Type of content section (list/text)
  #   content: |
  #     - **Treasurer:** Managed all the financial operations of the graduate student organization, Bangladesh Student Association (BSA) at UAB, 2023
  #     - **Judge:** Served as a judge of Summer 2023 Undergraduate Research Expo, UAB
  #     - **Competitive Programming Instructor:** Conducted workshops on problem-solving especially using C and C++ with dedicated sessions on Data Structure and Algorithms at Leading University
  #     - **Public Relations Officer:** Coordinated and managed several Intra-university programming contests for Leading University Computer Club (LUCC)


 # - **Security Assurance Agent:** Served as a Security Assurance Agent of the Bangladesh National Cadet Corps (BNCC), Leading University Platoon


  # - title: Recent Activities # Title for the section
  #   layout: text # Type of content section (list/text)
  #   content: |
  #     - Served as a judge of Summer 2023 Undergraduate Research Expo, UAB
  #     - Attended International Conference on Bangla Speech and Language Processing, 2019, SUST
  #     - Attended International Conference on Bangla Speech and Language Processing, 2018, SUST
  

  # - title: Test Score Information # Title for the section
  #   layout: text # Type of content section (list/text)
  #   content: |
  #     - **Graduate Record Examinations General Test (GRE):** Overall: 304, (Quantitative-159, Verbal-145, AWA-3.0)
  #     - **International English Language Testing System (IELTS):** Overall: 7.0, (Listening-7.0, Reading-6.0, Writing-6.0, Speaking-8.0)
  



  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in software engineering and programming languages some of my other interests and hobbies are:
  #     - Playing Cricket, Tennis
  #     - Hiking
  #     - Biking
  #     - Watching movies
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #    Look at this cool image  
  #    ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
references_title: Thanks to [Modern-Resume-Theme]


# to link external resource, to open in a new tab
# [link tilte](link url){:target="_blank" rel="noopener"}
# [Modern-Resume-Theme](https://github.com/sproogen/modern-resume-theme){:target="_blank" rel="noopener"}

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
